version: "2"
services:
  ldap: 
    container_name: ldap.edt.org
    ports:
      - "389:389"
    image: eescriba/ldapserver:greload
    networks: 
      - gandhi-net
  kerberos:
    container_name: kserver.edt.org
    depends_on: 
      - ldap 
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    image: eescriba/kerberos:greload
    networks:
      - gandhi-net
  homes: 
    container_name: homes.edt.org
    depends_on:
      - ldap
      - kerberos
    image: eescriba/userhomes:greload
    privileged: true
    networks:
      - gandhi-net
  samba:
    container_name: samba.edt.org
    ports: 
      - "139:139"
      - "445:445"
    image: eescriba/sambaserver:greload 
    privileged: true
    depends_on:
      - ldap
      - kerberos
      - homes
    volumes_from:
      - homes
    networks:
      - gandhi-net
  nfs:
    container_name: nfs.edt.org
    ports:
      - "111:111"
      - "2049:2049"
      - "20048:20048"
    image: eescriba/nfsserver:greload
    privileged: true
    depends_on:
      - ldap
      - kerberos
      - homes
      - samba
    volumes_from:
      - homes
    networks:
      - gandhi-net
networks:
  gandhi-net:
    ipam:
      config:
        - subnet: "172.30.0.0/16"
          gateway: "172.30.0.1"
