version: "2"
services:
  dns:
    container_name: dns.edt.org
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    privileged: true
    image: eescriba/dnsserver:greload
    networks:
      - gandhi-net 
  dhcp:
    container_name: dhcp.edt.org
    ports:
      - "67:67/udp"
      - "67:67/tcp"
    image: eescriba/dhcpserver:greload
    privileged: true
    networks:
      - gandhi-net
    depends_on:
      - dns
  ldap: 
    container_name: ldap.edt.org
    ports:
      - "389:389"
    image: eescriba/ldapserver:greload
    depends_on:
      - dhcp
    networks: 
      - gandhi-net
  kerberos:
    container_name: kserver.edt.org
    depends_on: 
      - ldap 
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    image: eescriba/kerberos:greload
    networks:
      - gandhi-net
  homes: 
    container_name: homes.edt.org
    depends_on:
      - ldap
      - kerberos
    image: eescriba/userhomes:greload
    privileged: true
    networks:
      - gandhi-net
  samba:
    container_name: samba.edt.org
    ports: 
      - "139:139"
      - "445:445"
    image: eescriba/sambaserver:greload 
    privileged: true
    depends_on:
      - homes
    volumes_from:
      - homes
    networks:
      - gandhi-net
  nfs:
    container_name: nfs.edt.org
    ports:
      - "111:111"
      - "2049:2049"
      - "20048:20048"
    image: eescriba/nfsserver:greload
    privileged: true
    depends_on:
      - samba
    volumes_from:
      - homes
    networks:
      - gandhi-net
  sshd:
    container_name: sshd.edt.org
    ports: 
      - "1022:22"
    image: eescriba/sshdserver:greload
    privileged: true
    depends_on:
      - nfs
    networks:
      - gandhi-net
  http:
    container_name: http.edt.org
    ports:
      - "80:80"
    image: eescriba/httpserver:greload
    privileged: true
    depends_on: 
      - sshd
    networks:
      - gandhi-net
networks:
  gandhi-net:
    ipam:
      config:
        - subnet: "172.30.0.0/16"
          gateway: "172.30.0.1"
