docker push eescriba/ldapserver:greload
docker push eescriba/kerberos:greload
docker push eescriba/userhomes:greload
docker push eescriba/sambaserver:greload
docker push eescriba/nfsserver:greload
docker push eescriba/dhcpserver:greload
docker push eescriba/dnsserver:greload
docker push eescriba/sshdserver:greload
docker push eescriba/sambahost:greload
docker push eescriba/nfshost:greload
docker push eescriba/httpserver:greload
